### ISSUE TITLE
No functions found

### ISSUE THREAD

**Issue by AlexAltea** [williballenthin/python-idb#22]
I have an `.i64` file created with IDA Pro 7.0.170914 on Windows. It contains 12581 functions, few of which are named. When trying to get the list of functions with python-idb v0.3.6,`api.idautils.Functions()` returns an empty list.

```python
import idb
with idb.from_file('file.i64') as db:
    api = idb.IDAPython(db)
print(api.idautils.Functions())
```
Output is `[]`.

Since the database is a bit large for attachments, and I'd rather not leave it in a public place I have emailed it to you directly.

**Comment by williballenthin** [comment]
Hey @AlexAltea thanks for reporting this issue. I've received the file and will be triaging the bug this evening. I'll post an update here once I know a bit more.

**Comment by williballenthin** [comment]
Alright, I think I've identified the issue. There are three relevant facts:

  - I have been parsing the index field of a netnode as a signed number, and
  - your database contains addresses in which the top bit is set, and
  - when IDA stores function metadata it places the address in a netnode index field.

So, when python-idb went looking for function metadata, it would retrieve numbers it interpreted as negative, then say "these don't look like addresses that fall within any segment (because they are negative)", and decide there was nothing available.

Next step is to work through the codebase and figure out exactly where I have been making bad assumptions about this netnode index field. Fortunately, the unit test coverage is pretty good, so I hope this won't take too long.

More updates to come.

**Comment by williballenthin** [comment]
commits 49409fea705c3de5ed85b8de667413c2457ffe4b and c39a9467a47684587aea06db15e646b18e9aef55 address the issue described here. in my testing, the script provided by @AlexAltea now returns 12,581 functions (the same as IDA!).

once I can construct a test idb and unit test demonstrating things now work as expected, i'll close out this issue and tag v0.4.0 (had to break an API contract on what index values look like).

**Comment by williballenthin** [comment]
@AlexAltea if you pull from master now, then thinks *should* work. let me know how that goes for you.

**Comment by williballenthin** [comment]
unit test added in 55ff49044507fb3563a09469d7a360735da8a062, we're covered for the future.

Thanks again @AlexAltea for reporting the issue.

**Comment by AlexAltea** [comment]
Works perfect, thank you!
